language: perl
before_install:
  - export PERL_CPANM_OPT="--verbose --no-interactive $( echo $PERL_CPANM_OPT | sed 's/--skip-satisfied//' )"
perl:
  - "5.20-extras"
  - "5.20"
  - "5.18-extras"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
